server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: auth_mock-api
  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  file:
    name: logs/auth_mock-api.log