server:
  port: 8084
  servlet:
    context-path: /auth_mock_api
spring:
  application:
    name: auth_mock-api
logging:
  file:
    name: logs/auth_mock-api.log
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
