server:
  port: 8084
  servlet:
    context-path: /auth_mock_api
spring:
  application:
    name: auth_mock-api
  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  file:
    name: logs/auth_mock-api.log